### ISSUE TITLE
Edit Question Title

### ISSUE THREAD

**Issue by Jarrett0203** [CS3219-AY2324S1/ay2324s1-course-assessment-g48#39]
Not sure if it was intended not to let user edit title

**Comment by huanghao1998** [comment]
Yes it's intended, because we dun allow multiple same title

**Comment by Jarrett0203** [comment]
> Yes it's intended, because we dun allow multiple same title

why not just check for duplicate in db? Otherwise if admin make mistake then cannot change

**Comment by huanghao1998** [comment]
Yap i see,  we can change in the future, but it is not important for now
