### ISSUE TITLE
Going into an api directly without logging in should redirect to 401

### ISSUE THREAD

**Issue by Douglch** [CS3219-AY2324S1/ay2324s1-course-assessment-g48#70]
EDIT:
This only happens on localhost and not on leetpal so alls good :shipit: 

Description:
This can be bad especially when an anon user tries to match another logged in user.

Steps to replicate:
1. Open incognito window
2. Put http://localhost:3000/matching into url

Anon user able to go into page without logging in:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g48/assets/48470532/5c7fbd5e-e722-49e8-a8be-1cb82a351b6c)

This is what happens to both the logged in user and the incognito user when they both try to match. They are matched together but are unable to proceed and face error 401.

Logged in user:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g48/assets/48470532/19cee05e-3fac-415e-8867-dc79df87e28a)

Anon user:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g48/assets/48470532/5d0d0432-88f3-425b-8bd5-8ab55cb4ccf2)

**Comment by Jarrett0203** [comment]
is there any api call when just navigating to matching page? if not it's ok, i just want to know exactly where to router.push, ideally it would be immediately after an api call throws 401.
